#!/bin/sh

# login gcloud
gcloud auth activate-service-account --key-file=/root/conf/${SERVICE_ACCOUNT_JSONFILE}
gcloud config set project `cat /root/conf/${SERVICE_ACCOUNT_JSONFILE}| grep project_id|cut -d "\"" -f4`

certbot renew

\cp -f /etc/letsencrypt/live/${TARGET_DOMAIN}/* /root/cert
